// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6pDZR5dH8SIR-KGk1WhWOwWHvrgHr-aA',
    appId: '1:109314154382:web:ad68bb3740d1c3e34ccedf',
    messagingSenderId: '109314154382',
    projectId: 'temple-directory-india',
    authDomain: 'temple-directory-india.firebaseapp.com',
    storageBucket: 'temple-directory-india.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqohirMdWgc4kSpR8ccJamu5UtevSj5z8',
    appId: '1:109314154382:android:d2e607c7a242743c4ccedf',
    messagingSenderId: '109314154382',
    projectId: 'temple-directory-india',
    storageBucket: 'temple-directory-india.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXp6B-JyKzapqt6E02X1AMSiCXtNuM6Ec',
    appId: '1:109314154382:ios:262247718f97cde64ccedf',
    messagingSenderId: '109314154382',
    projectId: 'temple-directory-india',
    storageBucket: 'temple-directory-india.firebasestorage.app',
    iosBundleId: 'com.example.templeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXp6B-JyKzapqt6E02X1AMSiCXtNuM6Ec',
    appId: '1:109314154382:ios:262247718f97cde64ccedf',
    messagingSenderId: '109314154382',
    projectId: 'temple-directory-india',
    storageBucket: 'temple-directory-india.firebasestorage.app',
    iosBundleId: 'com.example.templeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6pDZR5dH8SIR-KGk1WhWOwWHvrgHr-aA',
    appId: '1:109314154382:web:79d1bb6c89367fb94ccedf',
    messagingSenderId: '109314154382',
    projectId: 'temple-directory-india',
    authDomain: 'temple-directory-india.firebaseapp.com',
    storageBucket: 'temple-directory-india.firebasestorage.app',
  );
}
